Repository MaKsY2/secret_santa, pull requests merged in 2023-01, with the labels that each got.

#6 groups
  spbstu_ss/src/controllers.rs
  spbstu_ss/src/controllers/groups_controller.rs
  spbstu_ss/src/controllers/users_controller.rs
  spbstu_ss/src/main.rs
  spbstu_ss/src/models.rs
  spbstu_ss/src/models/group_model.rs
  spbstu_ss/src/models/user_model.rs
  spbstu_ss/src/schema.rs
Labels: enhancement

#7 memberships models and controller
  spbstu_ss/migrations/2023-01-04-140439_create_users_to_groups/down.sql
  spbstu_ss/migrations/2023-01-04-140439_create_users_to_groups/up.sql
  spbstu_ss/migrations/2023-01-06-210808_membership/down.sql
  spbstu_ss/migrations/2023-01-06-210808_membership/up.sql
  spbstu_ss/src/controllers.rs
  spbstu_ss/src/controllers/memberships_controller.rs
  spbstu_ss/src/models.rs
  spbstu_ss/src/models/membership_model.rs
  spbstu_ss/src/schema.rs
Labels: enhancement

#8 santas model and controller
  spbstu_ss/Cargo.lock
  spbstu_ss/Cargo.toml
  spbstu_ss/migrations/2023-01-04-140448_create_santas/up.sql
  spbstu_ss/src/controllers.rs
  spbstu_ss/src/controllers/groups_controller.rs
  spbstu_ss/src/controllers/santas_controller.rs
  spbstu_ss/src/main.rs
  spbstu_ss/src/models.rs
  spbstu_ss/src/models/santa_model.rs
  spbstu_ss/src/schema.rs
Labels: enhancement

#10 nedodelano
  spbstu_ss_client/.gitignore
  spbstu_ss_client/Cargo.lock
  spbstu_ss_client/Cargo.toml
  spbstu_ss_client/src/main.rs
Labels: enhancement

#9 rest crud for memberships
  spbstu_ss/src/controllers/memberships_controller.rs
  spbstu_ss/src/main.rs
Labels: enhancement

#13 Vlad/rocket
  spbstu_ss/src/main.rs
Labels: enhancement

#17 schema fix 2
  spbstu_ss/src/controllers/groups_controller.rs
  spbstu_ss/src/controllers/memberships_controller.rs
  spbstu_ss/src/controllers/santas_controller.rs
  spbstu_ss/src/controllers/users_controller.rs
  spbstu_ss/src/lib.rs
  spbstu_ss/src/models/group_model.rs
  spbstu_ss/src/models/membership_model.rs
  spbstu_ss/src/models/santa_model.rs
  spbstu_ss/src/models/user_model.rs
  spbstu_ss/src/myschema.rs
Labels: enhancement

#18 jwt exp fix
  spbstu_ss/src/auth.rs
  spbstu_ss/src/myschema.rs
Labels: minor fix

#20 final fixes
  spbstu_ss/migrations/2023-01-04-140448_create_santas/up.sql
  spbstu_ss/migrations/2023-01-06-210808_membership/up.sql
  spbstu_ss/src/main.rs
Labels: enhancement, minor fix

#22 groups console commands done
  spbstu_ss_client/src/main.rs
Labels: enhancement

#23 Matvey/console
  spbstu_ss_client/src/main.rs
Labels: enhancement

#24 Update README.md
  README.md
Labels: documentation
